services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://neondb_owner:npg_hLYef9pVu8dj@ep-round-fire-aoslwbbu-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

  frontend: # <--- CHÚ Ý: KÉO NÓ RA NGOÀI CHO THẲNG HÀNG VỚI BACKEND
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
